baseurl = "https://colonelpopcorn.github.io"
languageCode = "en-us"
title = "colonelpopcorn writes software"
theme = "hugo-cards"
themesDir = "themes"
paginate = 6

[params]
  builtBy = "colonelpopcorn"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = "https://twitter.com/c0l0nelp0pc0rn1
  github = "http://github.com/colonelpopcorn"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  custom_css = ["css/custom.css"]

  [params.copyright]
     name = "Jonathan Ling"
     link = "https://jonathanling.net"
